export const LOGIN_START = 'LOGIN_START'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'
export const LOGOUT = 'LOGOUT'
export const SET_LOGIN_REDIRECT_PATH = 'SET_LOGIN_REDIRECT_PATH'

export const NEW_POST_START = 'NEW_POST_START'
export const NEW_POST_SUCCESS = 'NEW_POST_SUCCESS'
export const NEW_POST_FAIL = 'NEW_POST_FAIL'
export const NEW_POST = 'NEW_POST'

export const SET_NEW_POST_REDIRECT_PATH = 'SET_NEW_POST_REDIRECT_PATH'

export const NEW_POST_INIT = 'NEW_POST_INIT'

export const FETCH_POSTS_START = 'FETCH_POSTS_START'
export const FETCH_POSTS_SUCCESS = 'FETCH_POSTS_SUCCESS'
export const FETCH_POSTS_FAIL = 'FETCH_POSTS_FAIL'
export const FETCH_POSTS = 'FETCH_POSTS'

export const FETCH_POSTS_BY_ID_START = 'FETCH_POSTS_BY_ID_START'
export const FETCH_POSTS_BY_ID_SUCCESS = 'FETCH_POSTS_BY_ID_SUCCESS'
export const FETCH_POSTS_BY_ID_FAIL = 'FETCH_POSTS_BY_ID_FAIL'
export const FETCH_POSTS_BY_ID = 'FETCH_POSTS_BY_ID'

export const DELETE_POST_START = 'DELETE_POST_START'
export const DELETE_POST_SUCCESS = 'DELETE_POST_SUCCESS'
export const DELETE_POST_FAIL = 'DELETE_POST_FAIL'
export const DELETE_POST = 'DELETE_POST'